[package]
name = "life"
version = "0.1.0"
authors = ["Higor Silva <higor.slva@outlook.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
